export const animalEmojis = [
  "🐶",
  "🐱",
  "🐭",
  "🐹",
  "🐰",
  "🦊",
  "🦝",
  "🐻",
  "🐼",
  "🦄",
  "🐨",
  "🐯",
  "🦁",
  "🐮",
  "🐷",
  "🐸",
  "🐵",
  "🐒",
  "🦍",
  "🐔",
  "🐧",
  "🐦",
  "🐤",
  "🦆",
  "🦢",
  "🦉",
  "🦚",
  "🦜",
  "🐍",
  "🐢",
  "🦎",
  "🐊",
  "🐢",
  "🦕",
  "🦖",
  "🐙",
  "🦔",
  "🐿️",
  "🦡",
  "🦛",
  "🦏",
  "🐆",
  "🐅",
  "🐃",
  "🐂",
  "🐄",
  "🐪",
  "🐫",
  "🐘",
  "🦒",
];

export const petNames = [
  "Max",
  "Bella",
  "Charlie",
  "Lucy",
  "Leo",
  "Luna",
  "Oliver",
  "Milo",
  "Chloe",
  "Simba",
  "Rocky",
  "Coco",
  "Tiger",
  "Molly",
  "Jax",
  "Sophie",
  "Oscar",
  "Lola",
  "Shadow",
  "Daisy",
  "Bailey",
  "Zoe",
  "Bentley",
  "Mia",
  "Leo",
  "Ruby",
  "Buddy",
  "Lily",
  "Rosie",
  "Jack",
  "Cleo",
  "Toby",
  "Kitty",
  "Maximus",
  "Sadie",
  "Gizmo",
  "Mocha",
  "Zeus",
  "Nala",
  "Charlie",
  "Misty",
  "Sammy",
  "Maddie",
  "Cooper",
  "Penny",
  "Lily",
  "Duke",
  "Emma",
  "Lulu",
  "Teddy",
];

export const funnyPetEpitaphs = [
  "Chased one too many squirrels.",
  "Chief Squirrel Chaser, finally resting.",
  "Master of stealing socks and hearts.",
  "In dog heaven, all the tennis balls are new.",
  "Left paw prints on our hearts and furniture.",
  "Chased every tail in sight, now chasing rainbows.",
  "Went to the big dog park in the sky.",
  "Never met a treat they didn't like.",
  "Finally caught that elusive tail.",
  "Barked at everything, loved by everyone.",
  "Ate all the treats, left all the joy.",
  "Knocked over one too many trash cans.",
  "Gone to join the cat-chasing society.",
  "Chirps and purrs, now among the stars.",
  "Flew high, chirped loud, will be missed.",
  "Lived nine lives, now on a cosmic adventure.",
  "Brought joy and fur wherever they roamed.",
  "Left paw prints and nose smudges on our hearts.",
  "Chased mice and dreams with equal determination.",
  "Loved belly rubs, detested bath time.",
  "Forever in our laps, forever in our hearts.",
  "Brought endless laughter and hairballs.",
  "Made every day a dog day, rain or shine.",
  "Paw-sitively the best cat we ever had.",
  "Chewed shoes, stole hearts.",
  "Chirped and purred their way into our lives.",
  "Played fetch with stars and dreams.",
  "Came, meowed, conquered.",
  "Unrivaled in napping expertise.",
  "Brought more joy than a bag of catnip.",
];
